export const HOME = "/";
export const LOGIN = "/login";
export const SIGN_UP = "/signup";
export const NOT_FOUND = "/not-found";
export const CHACKOUT = '/chack-out';
export const PAYMENT = '/payment';
export const SHOP = '/shop';
export const SALESORDER= '/sales&order';
export const SEARCHITEM = '/search-item/:productName';
